### ISSUE TITLE
Large_Intestine-counts.csv missing from figshare

### ISSUE THREAD

**Issue by jasonserviss** [czbiohub/tabula-muris#211]
FYI it would appear that the 00_facs_raw_data/FACS/Large_Intestine-counts.csv file is missing from the figshare [download](https://figshare.com/articles/Single-cell_RNA-seq_data_from_Smart-seq2_sequencing_of_FACS_sorted_cells/5715040).

**Comment by nsalomonis** [comment]
Following up on this issue as well. The file does not appear in GEO or the HCA data browser.
