### ISSUE TITLE
Missing genes

### ISSUE THREAD

**Issue by amisharin** [czbiohub/tabula-muris#216]
Hello BioHub team, thank you for creating this resource. I noticed that some genes are not on the list or in the counts tables, for example, Siglecf or Spp1. Could you, please, clarify why? Thank you.

**Comment by aopisco** [comment]
Hi @amisharin, we're using a reference that has missing genes - we're currently realigning the data to the gencode reference and will be sharing an updated version within the next couple of weeks

**Comment by amisharin** [comment]
Thank you, Angela, it makes sense now. 
I assume that update will be announced via GitHub, correct?

**Comment by aopisco** [comment]
yes, we'll leave a note in the repo such that everyone is aware but I'll make sure to ping you

**Comment by amisharin** [comment]
Thank you, very kind of you. 
And thank you for maintaining and improving this resource. 
Closing this issue.
