### ISSUE TITLE
Questions about the  droplet data of lung and Trachea in figshare 

### ISSUE THREAD

**Issue by liuqivandy** [czbiohub/tabula-muris#217]
Hello, I downloaded droplet data from figshare. The data of most tissues looks fine, but  two of lung files (/Lung-10X_P8_12,  /Lung-10X_P8_13) and the Trachea tissue (./Trachea-10X_P8_14,        ./Trachea-10X_P8_15) has some problems. They included all the cells instead of filtered cells, so they all have 737280 cells there. 
 Thanks!
Qi

**Comment by aopisco** [comment]
@liuqivandy did you try using the data here: https://github.com/czbiohub/tabula-muris-vignettes/tree/master/data
