### ISSUE TITLE
Mouse ID Annotation

### ISSUE THREAD

**Issue by davisidarta** [czbiohub/tabula-muris#219]
Hello, Tabula Muris Team!

I'm using some of your data for further analysis in several tissues. I'm, however, confused about the mouse ID annotations. What do the numbers mean? Is there any information regarding the exact mouse age (11,12,..., or 15 weeks)?

I'm making this question here because I was confused at whom should I address this question to (20 PIs in the paper).

Thanks in advance!

**Comment by aopisco** [comment]
Hi @davisidarta! Tabula Muris is a single age -- 3m -- so the mouse ids are just identifiers to tell you from which animal is each cell coming from. Does it help?

**Comment by davisidarta** [comment]
Hi @aopisco! Thanks for such a quick answer. It doesn't, really, as one of the key points I'm interested in are eventual variations in the cellular landscape along small age intervals. 

Is there any chance someone in the Consortium has kept note of mice exact weekly age as they were sequenced? If so, this would be of immense value for my work!

**Comment by aopisco** [comment]
this is the best I got, thanks to @nschaum 

Mouse ID	Month of birth	Arrival date	Sac date
3_8_M	3/2017	6/13/2017	6/15/2017
3_9_M	3/2017	6/13/2017	6/15/2017
3_10_M	3/2017	6/13/2017	6/16/2017
3_11_M	3/2017	6/13/2017	6/16/2017
3_38_F	3/2017	6/27/2017	7/7/2017
3_39_F	3/2017	6/27/2017	7/7/2017
3_56_F	4/2017	7/5/2017	7/20/2017
3_57_F	4/2017	7/5/2017	7/20/2017
