### ISSUE TITLE
Mitochondrial encoded genes

### ISSUE THREAD

**Issue by jmzvillarreal** [czbiohub/tabula-muris#221]
Hi,
I am reanalyzing the datasets from bladder (Smartseq and 10X), I usually use the % of mitochondrial genes as a metric of cell QC and I find that there are no mt-genes in both datasets... Why is that ? I tried to find out in the methods but I could not...
Thanks in advance !
Jaime.

**Comment by aopisco** [comment]
Hi @jmzvillarreal, the reference we used didn't have mitochondrial genes so they are not part of the objects. Best, Angela

**Comment by jmzvillarreal** [comment]
Hi @aopisco , why did you exclude mitochondrial genes from your reference ?
Thanks!

**Comment by aopisco** [comment]
@jmzvillarreal no, the reference did not contain them and we did not realize it until recently. We have realigned the data though, if you're interested in unprocessed gene counts tables?

**Comment by Brunox13** [comment]
> @jmzvillarreal no, the reference did not contain them and we did not realize it until recently. We have realigned the data though, if you're interested in unprocessed gene counts tables?

That would be helpful, please!
Thank you!

**Comment by aopisco** [comment]
all available here: https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis/?region=us-west-2


for h5ad: s3://czb-tabula-muris-senis/Data-to-reproduce-figures/mutation-analysis-objs/adata_genecode_counts_for_gatk_with_metadata_and_embeddings.h5ad

**Comment by DennisPost10** [comment]
> all available here: https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis/?region=us-west-2
> 
> for h5ad: s3://czb-tabula-muris-senis/Data-to-reproduce-figures/mutation-analysis-objs/adata_genecode_counts_for_gatk_with_metadata_and_embeddings.h5ad

Are there already raw/unprocessed h5ad files available with realigned data (containing all genes) for droplet and facs?
I am looking for something like the "tabula-muris-senis-droplet-official-raw-obj.h5ad" file but with all genes.

**Comment by flde** [comment]
Thanks for your incredible work! 

In the original paper it states that 10x were mapped with CellRanger version 2.0.1 which is mm10. I was just wondering why the mt-genes are missing. 

Is it possible to access the updated raw data count tables other then via AWS? I think it would be quite helpful for the community to have fluent access to the raw count tables with mt genes for normalization and comparison of data sets.

**Comment by flde** [comment]
Many thanks for your great work and the AWS link. 

I am also interested in getting count tables with mt-gene counts. So far I tried tabula-muris-senis-droplet-official-raw-obj.h5ad which seems more complete but it has not stored mt-genes. 

Could you point me to the right directory? Is there a merged file of all FACS tissues? It would be great to have that information for proper scaling.

**Comment by alexisvdb** [comment]
I noticed that the data in this file does not contain integer values, so I guess it has been processed (normalized? rescaled to range 0 to 10?) in some way. 
s3://czb-tabula-muris-senis/Data-to-reproduce-figures/mutation-analysis-objs/adata_genecode_counts_for_gatk_with_metadata_and_embeddings.h5ad

I wonder if there is also a file available with the original raw count data?

**Comment by uqjlu8** [comment]
I've realigned the 10X fastq data (Marrow, 1m) to the reference mouse genome (with mtDNA). There is no mtDNA in any of the cells. I am guessing the mtDNA was not part of the original sequencing library used to amplify the scRNA seq data in the first place. Can someone confirm it for me please. Thanks

**Comment by aopisco** [comment]
correct, mt genes were not part of the original alignment gtf

**Comment by IdRose** [comment]
@alexisvdb did you end up finding an original raw count matrix with mtDNA?
