### ISSUE TITLE
Which version of Seurat you are using

### ISSUE THREAD

**Issue by beyondpie** [czbiohub/tabula-muris#222]
Hi,
I try to follow the codes from the 00_data_ingest to analyze the source data. But I found that most of the functions related with Seurat v3.0 cannot be run. When I install an old version, such as 2.3, also lots of functions are lost. 

So would you please tell me which version of Seurat you are using  so that I can repeat the data analysis procedure? 
Thanks
Songpeng

**Comment by aopisco** [comment]
@beyondpie did you check issue #220 ?

**Comment by beyondpie** [comment]
Thanks  a lot for your quick response!
I will try that. Hope Seurat 2.3.4 is OK.
