### ISSUE TITLE
Shiny App code

### ISSUE THREAD

**Issue by jungminchoilab** [czbiohub/tabula-muris#224]
Dear tabula-muris team,

This is a great resource. Thanks so much for sharing.
I was wondering if you could share your shiny app code so I could visualize my scRNA-Seq data (Seurat v3.0 object) interactively.

Best,
Jungmin

**Comment by aopisco** [comment]
@jungminchoi have you try using cellxgene https://github.com/chanzuckerberg/cellxgene ?

**Comment by jungminchoi** [comment]
@aopisco Thanks for your prompt response. This is looking great but it does not look like it is compatible with Seurat yet if I understood correctly. Is this what was used in tabula-muris (https://tabula-muris.ds.czbiohub.org/) website?

**Comment by aopisco** [comment]
@jungminchoi that's a question for @neevor. As for using cellxgene with Seurat objects check this out: https://bioconda.github.io/recipes/r-sceasy/README.html

**Comment by jungminchoi** [comment]
@aopisco Thanks!

**Comment by neevor** [comment]
@jungminchoi if you can use cellxgene that is the way to go. For the tabula muris site it's just a static website with pre-generated images, but the code used for any of the plots is in the notebooks in the repo. cellxgene is much easier and more flexible for a web interface though.
