### ISSUE TITLE
Gene Names

### ISSUE THREAD

**Issue by osolari** [czbiohub/tabula-muris#225]
How can one go from your name convention back to the standard convention "DAB2,DAD1,DAGLA,DAK,DAO,DAPK1 ..."

**Comment by aopisco** [comment]
Hi @osolari, we use the official gene symbol for mouse, but the gene symbols you have are the human ones. Can you please clarify your question?

**Comment by osolari** [comment]
Oh, there was a big mix-up here. Apologies! and thanks for the reponse.
