### ISSUE TITLE
Can I use one or two figures from the data

### ISSUE THREAD

**Issue by vijaykumarmuley** [czbiohub/tabula-muris#227]
Hello, 
I would like to use two figures from the data folder as below for my non-profit research work.
I was wondering if there would any issue with copyrights and permissions. 

https://github.com/czbiohub/tabula-muris/blob/master/02_figure2/facs_tsne_by_tissue.pdf
https://github.com/czbiohub/tabula-muris/blob/master/02_figure2/facs_tsne_by_cell_ontology_class.pdf
Best regards

**Comment by aopisco** [comment]
@vijaykumarmuley sorry for only seeing this message now, please check with Nature regarding permissions
