### ISSUE TITLE
A question about Bladder-counts data and their annotations in FACS data of Tabula-Muris

### ISSUE THREAD

**Issue by AllenWu18** [czbiohub/tabula-muris#228]
Hi, I just wanted to use the Bladder-counts data of FACS folder and their annotations to do some analysis, but I found that the number of Bladder data samples seemed not to match their labels' number. In other words, I found there are 1638 cells in the Bladder-counts.csv, but the labels are only 1287. So how should I use the data? For Now I don't know what cell has its label or not.

**Comment by aopisco** [comment]
@AllenWu18 I'd suggest you use the Tabula Muris Senis Bladder object from [here](https://figshare.com/articles/dataset/Tabula_Muris_Senis_Data_Objects/12654728)
If you're only interested in the 3m data just subset the object for `age=3m`

**Comment by AllenWu18** [comment]
Well, I went to the URL above and wanted to download the data, but it just showed
{"message": "Insufficient permissions", "code": "InsufficientPermissions"}
:(

**Comment by AllenWu18** [comment]
OK I can download the data now. Let me load the new data and have a look. 
THX :)
