### ISSUE TITLE
Transcription factor analysis for Fig 5 

### ISSUE THREAD

**Issue by singcell** [czbiohub/tabula-muris#229]
How did you perform transcription factor analysis for Fig 5 and Extended Data Fig. 10? If any TF is uniquely expressed and but at lower leevel would you assign to some cell type or in other language what was your cell-type assigning criteria?

Can you share the list of  1,016 transcription factors that you analyzed in your data.

**Comment by aopisco** [comment]
@singcell the code and files are available here https://github.com/czbiohub/tabula-muris/tree/master/23_tf_analysis
