### ISSUE TITLE
AWS fastq file metadata

### ISSUE THREAD

**Issue by gouinK** [czbiohub/tabula-muris#230]
Hi all, thank you for providing this great dataset on AWS. I was wondering if there is a metadata or annotation file that describes each of the samples in the 'senis/10x/fastq/' folder? Thanks!

**Comment by aopisco** [comment]
hi @gouinK, are you referring to the data in Tabula Muris (this repo) or Tabula Muris Senis (https://github.com/czbiohub/tabula-muris-senis)?

**Comment by gouinK** [comment]
Yes that is correct

**Comment by aopisco** [comment]
@gouinK the most complete metadata is the csv in here https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE149590
do you want to get the fastq files and rerun them through cellranger or other pipeline but get the correct metadata?

**Comment by gouinK** [comment]
Perfect, that looks like I can get the annotation from the prefix on the cell barcode, thanks so much!
Yes I plan to process this with cellranger v4 so that I can compare some of your mammary gland data to my own generated data.
