### ISSUE TITLE
looking for genome annotation used (mm10plus)

### ISSUE THREAD

**Issue by ChristophH** [czbiohub/tabula-muris#233]
Hi

Thank you for having such a neatly organized repo. Makes it really easy to reproduce everything.
However, I am missing one thing. In the paper you say the reads were aligned to the `mm10plus genome`. Could you point me to he exact feature annotation file for that version of the genome? I can only find GRCm38/mm10 and don't know what the `plus` part means. I am looking for the GTF, GFF or whatever file you used for htseq/Cellranger to create the raw counts.

Thank you,
Christoph

**Comment by yewero** [comment]
@ChristophH You may need the information [here](https://github.com/chanzuckerberg/cloud-rnaseq):

> The -plus part is the spiked ERCC RNA references

**Comment by aopisco** [comment]
@ChristophH the genome is available here:

`s3://czb-tabula-muris-senis/reference-genome/`

**Comment by yotamcons** [comment]
Following up on this - what version of the transcriptome did you use?
Do you know if its the same to Tabula-muris-senis?

**Comment by aopisco** [comment]
reference genome used available here `s3://czb-tabula-muris-senis/reference-genome/`

**Comment by yotamcons** [comment]
Hey again, I'm looking for the reference **transcriptome**, not genome

**Comment by aopisco** [comment]
yes, that is the one I sent you
