### ISSUE TITLE
Seurat object for entire integrated FACS dataset (ie what was used for Fig. 2)?

### ISSUE THREAD

**Issue by evaknichols** [czbiohub/tabula-muris#235]
Hello! 

First off, thanks so much for creating and maintaining this really excellent atlas resource! I look forward to using the data. 

I'm hoping to not have missed this on Figshare....But I can't seem to find a Seurat R object of the entire integrated FACS dataset (whereas I found one for each independent organ). 

Before attempting to make one myself, I thought to check in to make sure there isn't already one posted? If it's not posted, is it possible to have one posted? I want to avoid a situation where I can't reproduce Figure 2 in the paper with all of the same (or updated) annotations.

Thank you!

From,
Eva

**Comment by evaknichols** [comment]
Hi again--thought I would check in with additional information. 

Since first opening the issue, I decided to try Seurat's merge function to merge all 20 organ Seurat objects. However, I learned that I need to first update the objects using the UpdateSeuratObject. But, I was unable to update them--the error message stated "We are unable to convert Seurat objects less than 2.X to version 3.X. Please use dev_tools::install_version to install Seurat v2.3.4 and update your object to a 2.X object."

This method to install Seurat v2.3.4 failed (and others), likely due to R versioning issues. This issue is getting a bit out of hand for me to continue on my own, especially considering that even if I updated/merged objects, I might need to run the Seurat pipeline from scratch.

I'll consider opening an issue with the Seurat team, but if the Tab. Muris Consortium wants people to keep using the data, it would be super helpful to provide updated objects that everyone can use. For example I might be forced to reconsider using another sc dataset as a testbed.

Thanks!

From,
Eva

**Comment by lincoln-harris** [comment]
@aopisco @olgabot what do you think? 

we'd like to use Tabula Muris for a spacial transcriptomics project but are running into backward compatibility issues. 

maybe the best move is to start with the raw cell-by-gene matrices and re-run clustering in Seurat?

**Comment by aopisco** [comment]
I would highly recommend using the tabula muris senis h5ad files that have raw counts in figshare to start
