### ISSUE TITLE
Access denied for downloading data files

### ISSUE THREAD

**Issue by naskomit** [czbiohub/tabula-muris#236]
Hi, and first thanks for this great dataset!
I am trying to download some data files from AWS. Listing works fine:
```
aws s3 ls --no-sign-request s3://czb-tabula-muris/TM_facs_mat.h5ad

2018-10-08 21:39:11  487706533 TM_facs_mat.h5ad
```
However I cannot copy:
```
aws s3 cp --no-sign-request s3://czb-tabula-muris/TM_facs_mat.h5ad .

fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
```
Is there something I am doing wrong? I don't know if this matters, but I am in Eastern Europe.

**Comment by aopisco** [comment]
that path does not exist -- please check the correct path for the object: https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis?region=us-west-2&tab=objects
