### ISSUE TITLE
Gene - Tissue - Cell Type association

### ISSUE THREAD

**Issue by MathiasBeller** [czbiohub/tabula-muris#240]
Hello, I am working on a project which requires information about the expression of each gene in the different cell types of various organs (averaged expression across the measured cells). Such a file exists e.g. for human single cell sequencing data provided via the Human Protein Atlas (file # 9 at https://www.proteinatlas.org/about/download). Does something similar exist also exist for the Tabula Muris dataset? If it does, I am sorry that I did not find it. Thank you very much in advance for your help! Best regards, Mathias

**Comment by aopisco** [comment]
Hi @MathiasBeller we did not compute such file

**Comment by MathiasBeller** [comment]
Thank you very much for the clarification. Best, Mathias
