### ISSUE TITLE
raw data in GSE109774 lacking 10x libraries

### ISSUE THREAD

**Issue by zyh4482** [czbiohub/tabula-muris#244]
Do raw data stored in [GSE109774](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE109774) only contain the Smart-Seq2 data? ENA and GEOdataset provide download links for fastq. [humancellatlas](https://data.humancellatlas.org/explore/projects/e0009214-c0a0-4a7b-96e2-d6a83e966ce0) also provide raw fastq files. But all of them are Smart-Seq2 data. The cell number is 44950, as reported by the TabulaMuris 2018 article. But there should be another 55656 cells sequenced using 10x 3' libraries. Is there another way to find these 10x fastq? I found the link to AWS bucket for this dataset but I couldn't download it due to denied access.

**Comment by aopisco** [comment]
All data is available here https://s3.console.aws.amazon.com/s3/buckets/czb-tabula-muris-senis?region=us-west-2&tab=objects
