### ISSUE TITLE
raw counts matrix with mitochondrial genes

### ISSUE THREAD

**Issue by IdRose** [czbiohub/tabula-muris#246]
Hi, I'm looking for a raw, not normalized nor scaled counts matrix for TMS which includes mtDNA. Here https://github.com/czbiohub/tabula-muris/issues/221 it is suggested to use this 
 file : adata_genecode_counts_for_gatk_with_metadata_and_embeddings.h5ad but the counts matrix was normalized...is it possible to find the raw counts matrix with mt anywhere?

**Comment by aopisco** [comment]
yes, in the same folder 

`s3://czb-tabula-muris-senis/Data-to-reproduce-figures/mutation-analysis-objs/adata_with_ercc_genecode_counts_for_gatk_with_metadata.h5ad`

**Comment by IdRose** [comment]
much appreciated! is there by any chance something similar but for the raw droplet data with mtDNA?

**Comment by aopisco** [comment]
unfortunately I did make such object
