### ISSUE TITLE
Cell annotation

### ISSUE THREAD

**Issue by strawberry098** [czbiohub/tabula-muris#251]
I downloaded the .robj file for spleen FACS droplet data.  The metadata of the Seurat Object does not include a column of annotated cell types.  How can I retrieve this information? - Thanks.

**Comment by stanaka6** [comment]
I have the same situation when I download lung droplet data. On the other hand, I found a similar data set in Tabula Muris Senis (https://cellxgene.cziscience.com/collections/0b9d8a04-bb9d-44da-aa27-705bb65b54eb), which includes Seurat object and h5ad.

**Comment by aopisco** [comment]
@strawberry098 @stanaka6 thanks for your messages, to access the R compatible objects please download from [here](https://cellxgene.cziscience.com/collections/0b9d8a04-bb9d-44da-aa27-705bb65b54eb)

**Comment by aopisco** [comment]
the objects in the link are for Tabula Muris Senis, and Tabula Muris is contained in Tabula Muris Senis (`age="3m"`)
