### ISSUE TITLE
Upload the processed Seurat Objects to somewhere accessible

### ISSUE THREAD

**Issue by batson** [czbiohub/tabula-muris#4]

**Comment by simon-anders** [comment]
Hi Joshua et al.

Yes, getting the Seurat objects would be great! :-)

I was just trying to play with your Tabula Muris data but had trouble running the tissue analysis scripts. 

In the end, what I wanted to do is try to redo the t-SNE plots from Figure 2b of your BioaRxiv preprint and change the coloring, e.g., color by specific genes or whatever. 

So, if you could make the objects available, or at least the matrices with the t-SNE coodinates, that would be much appreciated, certainly not only by me. Hence: You think you'll get around to do this soon?

Thanks for making all data and code available!

Cheers
  Simon 
  (University of Heidelberg)

**Comment by batson** [comment]
Hi Simon!

Thanks for reaching out. We are in the process of redoing some of the annotations, actually, in response to some of the feedback received from refs and the community. After looking at the data further we decided to modify the normalization and scaling. As you can see from all the PR's in this repo, that work is progressing rapidly, and when it's all sorted we will upload the new R objects.

I'll try to remember to reply here when it's all done, but there will also be a blog post and some tweets to let the world know when we're done with this second pass.

**Comment by aopisco** [comment]
Hi Simon,

you can find all the data here: https://github.com/czbiohub/tabula-muris-vignettes/tree/master/data
Let us know if you need anything else!
